swagger: "2.0"
info:
  title: Space Ship Api
  description: made by Mike for demo purposes
  version: 1.0.0
#x-google-backend:
#  address: https://us-central1-mikes-demo2023.cloudfunctions.net
schemes:
  - https
paths:
  /refuelspaceship:
    post:
      x-google-backend:
        address: https://us-central1-mikes-demo2023.cloudfunctions.net/refuelspaceship
      tags:
        - SpaceShipRefuel
      description: Destination For spaceship
      operationId: refuelspaceship
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/SpaceShip"
      consumes:
        - "application/json"
      produces:
        - "application/text"
      responses:
        200:
          description: Success response
          schema:
            type: string
        500:
          description: Destination not determined yet
          schema:
            type: string
  /spaceshipdestination:
    post:
      x-google-backend:
        address: https://europe-west3-mikes-demo2023.cloudfunctions.net/spaceshipdestination
      tags:
        - SpaceShipDestination
      description: Destination For spaceship
      operationId: spaceshipdestination
      parameters:
        - in: body
          name: body
          required: true
          type: string
      consumes:
        - "application/json"
      produces:
        - "application/text"
      responses:
        200:
          description: Success response
          schema:
            type: string
        500:
          description: Destination not determined yet
          schema:
            type: string

definitions:
  SpaceShip:
    type: object
    properties:
      id:
        type: string
      captain:
        type: string
      location:
        type: string
      fuelleft:
        type: integer
      model:
        type: string
security:
  - api_key: [ ]
securityDefinitions:
  api_key:
    type: apiKey
    name: key
    in: query


#  my_google_jwt:
#    authorizationUrl: ''
#    flow: implicit
#    type: oauth2
#    x-google-issuer: serviceaccount_mike@${var2}.iam.gserviceaccount.com
#    x-google-audiences: ${var2}
#    x-google-jwks_uri: >-
#      https://www.googleapis.com/service_accounts/v1/jwk/serviceaccount_mike@${var2}.iam.gserviceaccount.com