POST https://europe-west3-mikes-demo2023.cloudfunctions.net/spaceshipdestination
Accept: application/text
Content-Type: application/json
Authorization: bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjYwODNkZDU5ODE2NzNmNjYxZmRlOWRhZTY0NmI2ZjAzODBhMDE0NWMiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJhenAiOiIzMjU1NTk0MDU1OS5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsImF1ZCI6IjMyNTU1OTQwNTU5LmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwic3ViIjoiMTA1OTQzNjYwODE3NTA1NzcyMDI3IiwiZW1haWwiOiJla2ltMTk3NzExQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJhdF9oYXNoIjoicEVSS245clVHMThSYVAwZGhyVnRlQSIsImlhdCI6MTY4NTQ3OTAzOCwiZXhwIjoxNjg1NDgyNjM4fQ.yLgwaQTBs_djAsi3duG4isu1qfn-TbvclxGewt3srGJpUV7Xfq5v4-sGXJfxV9L_8GMjXX2TINkFMqmLUqY3VYQOPjjvCgKpIHfvwFisOSxZFx1ER8479BVL9Zw2YvrF_74t5BiC4J7l-TJd8KDw4JiT9P06BBGne-iQrnzhIEW5AZkFn_VcaRrnKhz4rpkUVmnh6VcG0VxmvuluCgFQ4R8cdLpGvXv1U6oVsykxlecRR5p7RjyAX8pU1xD6RLBOUJB965ZNFCuY6qIC9ugnwHruNQcJoY8mQRj87mwo0P-KsmguS2wLbKtMvCQdqVWxr1btv0YOksATtP7fuaPq4w

{}